local _, DDT = ...

local locales = {
    enUS = {
        NO_DURABILITY = "No equipped items with durability found.",
        CURRENT_DURABILITY = "Current durability: %s.",
        LOW_DURABILITY = "LOW DURABILITY: %.1f%%",
        DURABILITY_LOSS = "You lost |cffffffff%.1f%%|r durability. Durability left: %s.",
        OPTIONS_MAJOR = "Enable major warning",
        OPTIONS_MAJOR_TOOLTIP = "Show large text and play a sound when entering an instance or delve below 80% durability.",
        OPTIONS_PORTAL = "Warn when using a seasonal dungeon portal",
        OPTIONS_PORTAL_TOOLTIP = "Also warn when using a current-season dungeon portal below 80% durability.",
        OPTIONS_FOLLOWUP = "Warn after durability loss",
        OPTIONS_FOLLOWUP_TOOLTIP = "Also warn after durability loss below 50% inside an instance or delve.",
        MAJOR_WARNING_CHANGED = "Major warning %s.",
        FOLLOWUP_WARNING_CHANGED = "Follow-up major warnings %s.",
        PORTAL_WARNING_CHANGED = "Seasonal dungeon portal warnings %s.",
        MAJOR_WARNING_STATUS = "Major warning is %s.",
        FOLLOWUP_WARNING_STATUS = "Follow-up warnings are %s.",
        PORTAL_WARNING_STATUS = "Seasonal dungeon portal warnings are %s.",
        ENABLED = "enabled",
        DISABLED = "disabled",
        ENABLED_PLURAL = "enabled",
        DISABLED_PLURAL = "disabled",
        HELP_WARNING = "Use /ddt warning on or /ddt warning off.",
        HELP_FOLLOWUP = "Use /ddt warning followup on or /ddt warning followup off.",
        HELP_PORTAL = "Use /ddt warning portal on or /ddt warning portal off.",
    },
    ptBR = {
        NO_DURABILITY = "Nenhum item equipado com durabilidade foi encontrado.",
        CURRENT_DURABILITY = "Durabilidade atual: %s.",
        LOW_DURABILITY = "DURABILIDADE BAIXA: %.1f%%",
        DURABILITY_LOSS = "Você perdeu |cffffffff%.1f%%|r de durabilidade. Durabilidade restante: %s.",
        OPTIONS_MAJOR = "Ativar aviso principal",
        OPTIONS_MAJOR_TOOLTIP = "Exibe um texto grande e toca um som ao entrar em uma instância ou imersão com menos de 80% de durabilidade.",
        OPTIONS_PORTAL = "Avisar ao usar um portal de masmorra da temporada",
        OPTIONS_PORTAL_TOOLTIP = "Também avisa ao usar um portal de masmorra da temporada atual com menos de 80% de durabilidade.",
        OPTIONS_FOLLOWUP = "Avisar após perda de durabilidade",
        OPTIONS_FOLLOWUP_TOOLTIP = "Também avisa após uma perda de durabilidade abaixo de 50% dentro de uma instância ou imersão.",
        MAJOR_WARNING_CHANGED = "Aviso principal %s.",
        FOLLOWUP_WARNING_CHANGED = "Avisos principais posteriores %s.",
        PORTAL_WARNING_CHANGED = "Avisos de portal de masmorra da temporada %s.",
        MAJOR_WARNING_STATUS = "O aviso principal está %s.",
        FOLLOWUP_WARNING_STATUS = "Os avisos posteriores estão %s.",
        PORTAL_WARNING_STATUS = "Os avisos de portal de masmorra da temporada estão %s.",
        ENABLED = "ativado",
        DISABLED = "desativado",
        ENABLED_PLURAL = "ativados",
        DISABLED_PLURAL = "desativados",
        HELP_WARNING = "Use /ddt warning on ou /ddt warning off.",
        HELP_FOLLOWUP = "Use /ddt warning followup on ou /ddt warning followup off.",
        HELP_PORTAL = "Use /ddt warning portal on ou /ddt warning portal off.",
    },
}

DDT.L = locales[GetLocale()] or locales.enUS
