local _, DDT = ...

local locales = {
    enUS = {
        NO_DURABILITY = "No equipped items with durability found.",
        CURRENT_DURABILITY = "Current durability: %s.",
        LOW_DURABILITY = "LOW DURABILITY: %.1f%%",
        DURABILITY_LOSS = "You lost |cffffffff%.1f%%|r durability. Durability left: %s.",
        OPTIONS_MAJOR = "Enable major warning",
        OPTIONS_MAJOR_TOOLTIP = "Show large text and play a sound when entering an instance or delve below 80% durability.",
        OPTIONS_PORTAL = "Warn when using a seasonal dungeon portal",
        OPTIONS_PORTAL_TOOLTIP = "Also warn when using a current-season dungeon portal below 80% durability.",
        OPTIONS_FOLLOWUP = "Warn after durability loss",
        OPTIONS_FOLLOWUP_TOOLTIP = "Also warn after durability loss below 50% inside an instance or delve.",
        MAJOR_WARNING_CHANGED = "Major warning %s.",
        FOLLOWUP_WARNING_CHANGED = "Follow-up major warnings %s.",
        PORTAL_WARNING_CHANGED = "Seasonal dungeon portal warnings %s.",
        MAJOR_WARNING_STATUS = "Major warning is %s.",
        FOLLOWUP_WARNING_STATUS = "Follow-up warnings are %s.",
        PORTAL_WARNING_STATUS = "Seasonal dungeon portal warnings are %s.",
        ENABLED = "enabled",
        DISABLED = "disabled",
        ENABLED_PLURAL = "enabled",
        DISABLED_PLURAL = "disabled",
        HELP_WARNING = "Use /ddt warning on or /ddt warning off.",
        HELP_FOLLOWUP = "Use /ddt warning followup on or /ddt warning followup off.",
        HELP_PORTAL = "Use /ddt warning portal on or /ddt warning portal off.",
    },
    deDE = {
        NO_DURABILITY = "Keine ausgerüsteten Gegenstände mit Haltbarkeit gefunden.",
        CURRENT_DURABILITY = "Aktuelle Haltbarkeit: %s.",
        LOW_DURABILITY = "NIEDRIGE HALTBARKEIT: %.1f%%",
        DURABILITY_LOSS = "Du hast |cffffffff%.1f%%|r Haltbarkeit verloren. Verbleibende Haltbarkeit: %s.",
        OPTIONS_MAJOR = "Große Warnung aktivieren",
        OPTIONS_MAJOR_TOOLTIP = "Zeigt großen Text an und spielt einen Ton ab, wenn du eine Instanz oder ein Tief unter 80 % Haltbarkeit betrittst.",
        OPTIONS_PORTAL = "Bei Benutzung eines saisonalen Dungeonportals warnen",
        OPTIONS_PORTAL_TOOLTIP = "Warnt auch bei Benutzung eines Dungeonportals der aktuellen Saison unter 80 % Haltbarkeit.",
        OPTIONS_FOLLOWUP = "Nach Haltbarkeitsverlust warnen",
        OPTIONS_FOLLOWUP_TOOLTIP = "Warnt auch nach Haltbarkeitsverlust unter 50 % innerhalb einer Instanz oder eines Tiefs.",
        MAJOR_WARNING_CHANGED = "Große Warnung %s.",
        FOLLOWUP_WARNING_CHANGED = "Nachfolgende große Warnungen %s.",
        PORTAL_WARNING_CHANGED = "Warnungen für saisonale Dungeonportale %s.",
        MAJOR_WARNING_STATUS = "Große Warnung ist %s.",
        FOLLOWUP_WARNING_STATUS = "Nachfolgende Warnungen sind %s.",
        PORTAL_WARNING_STATUS = "Warnungen für saisonale Dungeonportale sind %s.",
        ENABLED = "aktiviert", DISABLED = "deaktiviert",
        ENABLED_PLURAL = "aktiviert", DISABLED_PLURAL = "deaktiviert",
        HELP_WARNING = "Benutze /ddt warning on oder /ddt warning off.",
        HELP_FOLLOWUP = "Benutze /ddt warning followup on oder /ddt warning followup off.",
        HELP_PORTAL = "Benutze /ddt warning portal on oder /ddt warning portal off.",
    },
    esES = {
        NO_DURABILITY = "No se encontraron objetos equipados con durabilidad.",
        CURRENT_DURABILITY = "Durabilidad actual: %s.",
        LOW_DURABILITY = "DURABILIDAD BAJA: %.1f%%",
        DURABILITY_LOSS = "Has perdido un |cffffffff%.1f%%|r de durabilidad. Durabilidad restante: %s.",
        OPTIONS_MAJOR = "Activar aviso principal",
        OPTIONS_MAJOR_TOOLTIP = "Muestra texto grande y reproduce un sonido al entrar en una estancia o profundidad con menos del 80 % de durabilidad.",
        OPTIONS_PORTAL = "Avisar al usar un portal de mazmorra de temporada",
        OPTIONS_PORTAL_TOOLTIP = "También avisa al usar un portal de mazmorra de la temporada actual con menos del 80 % de durabilidad.",
        OPTIONS_FOLLOWUP = "Avisar tras perder durabilidad",
        OPTIONS_FOLLOWUP_TOOLTIP = "También avisa tras perder durabilidad por debajo del 50 % dentro de una estancia o profundidad.",
        MAJOR_WARNING_CHANGED = "Aviso principal %s.",
        FOLLOWUP_WARNING_CHANGED = "Avisos principales posteriores %s.",
        PORTAL_WARNING_CHANGED = "Avisos de portales de mazmorra de temporada %s.",
        MAJOR_WARNING_STATUS = "El aviso principal está %s.",
        FOLLOWUP_WARNING_STATUS = "Los avisos posteriores están %s.",
        PORTAL_WARNING_STATUS = "Los avisos de portales de mazmorra de temporada están %s.",
        ENABLED = "activado", DISABLED = "desactivado",
        ENABLED_PLURAL = "activados", DISABLED_PLURAL = "desactivados",
        HELP_WARNING = "Usa /ddt warning on o /ddt warning off.",
        HELP_FOLLOWUP = "Usa /ddt warning followup on o /ddt warning followup off.",
        HELP_PORTAL = "Usa /ddt warning portal on o /ddt warning portal off.",
    },
    esMX = {
        NO_DURABILITY = "No se encontraron objetos equipados con durabilidad.",
        CURRENT_DURABILITY = "Durabilidad actual: %s.",
        LOW_DURABILITY = "DURABILIDAD BAJA: %.1f%%",
        DURABILITY_LOSS = "Perdiste un |cffffffff%.1f%%|r de durabilidad. Durabilidad restante: %s.",
        OPTIONS_MAJOR = "Activar advertencia principal",
        OPTIONS_MAJOR_TOOLTIP = "Muestra texto grande y reproduce un sonido al entrar a una estancia o abismo con menos del 80 % de durabilidad.",
        OPTIONS_PORTAL = "Advertir al usar un portal de calabozo de temporada",
        OPTIONS_PORTAL_TOOLTIP = "También advierte al usar un portal de calabozo de la temporada actual con menos del 80 % de durabilidad.",
        OPTIONS_FOLLOWUP = "Advertir después de perder durabilidad",
        OPTIONS_FOLLOWUP_TOOLTIP = "También advierte después de perder durabilidad por debajo del 50 % dentro de una estancia o abismo.",
        MAJOR_WARNING_CHANGED = "Advertencia principal %s.",
        FOLLOWUP_WARNING_CHANGED = "Advertencias principales posteriores %s.",
        PORTAL_WARNING_CHANGED = "Advertencias de portales de calabozo de temporada %s.",
        MAJOR_WARNING_STATUS = "La advertencia principal está %s.",
        FOLLOWUP_WARNING_STATUS = "Las advertencias posteriores están %s.",
        PORTAL_WARNING_STATUS = "Las advertencias de portales de calabozo de temporada están %s.",
        ENABLED = "activada", DISABLED = "desactivada",
        ENABLED_PLURAL = "activadas", DISABLED_PLURAL = "desactivadas",
        HELP_WARNING = "Usa /ddt warning on o /ddt warning off.",
        HELP_FOLLOWUP = "Usa /ddt warning followup on o /ddt warning followup off.",
        HELP_PORTAL = "Usa /ddt warning portal on o /ddt warning portal off.",
    },
    frFR = {
        NO_DURABILITY = "Aucun objet équipé avec une durabilité n’a été trouvé.",
        CURRENT_DURABILITY = "Durabilité actuelle : %s.",
        LOW_DURABILITY = "DURABILITÉ FAIBLE : %.1f%%",
        DURABILITY_LOSS = "Vous avez perdu |cffffffff%.1f%%|r de durabilité. Durabilité restante : %s.",
        OPTIONS_MAJOR = "Activer l’avertissement principal",
        OPTIONS_MAJOR_TOOLTIP = "Affiche un grand texte et joue un son à l’entrée dans une instance ou un gouffre sous 80 % de durabilité.",
        OPTIONS_PORTAL = "Avertir lors de l’utilisation d’un portail de donjon saisonnier",
        OPTIONS_PORTAL_TOOLTIP = "Avertit aussi lors de l’utilisation d’un portail de donjon de la saison actuelle sous 80 % de durabilité.",
        OPTIONS_FOLLOWUP = "Avertir après une perte de durabilité",
        OPTIONS_FOLLOWUP_TOOLTIP = "Avertit aussi après une perte de durabilité sous 50 % dans une instance ou un gouffre.",
        MAJOR_WARNING_CHANGED = "Avertissement principal %s.",
        FOLLOWUP_WARNING_CHANGED = "Avertissements principaux ultérieurs %s.",
        PORTAL_WARNING_CHANGED = "Avertissements de portail de donjon saisonnier %s.",
        MAJOR_WARNING_STATUS = "L’avertissement principal est %s.",
        FOLLOWUP_WARNING_STATUS = "Les avertissements ultérieurs sont %s.",
        PORTAL_WARNING_STATUS = "Les avertissements de portail de donjon saisonnier sont %s.",
        ENABLED = "activé", DISABLED = "désactivé",
        ENABLED_PLURAL = "activés", DISABLED_PLURAL = "désactivés",
        HELP_WARNING = "Utilisez /ddt warning on ou /ddt warning off.",
        HELP_FOLLOWUP = "Utilisez /ddt warning followup on ou /ddt warning followup off.",
        HELP_PORTAL = "Utilisez /ddt warning portal on ou /ddt warning portal off.",
    },
    itIT = {
        NO_DURABILITY = "Nessun oggetto equipaggiato con integrità trovato.",
        CURRENT_DURABILITY = "Integrità attuale: %s.",
        LOW_DURABILITY = "INTEGRITÀ BASSA: %.1f%%",
        DURABILITY_LOSS = "Hai perso il |cffffffff%.1f%%|r di integrità. Integrità restante: %s.",
        OPTIONS_MAJOR = "Attiva avviso principale",
        OPTIONS_MAJOR_TOOLTIP = "Mostra un testo grande e riproduce un suono entrando in un'incursione, spedizione o voragine sotto l'80% di integrità.",
        OPTIONS_PORTAL = "Avvisa usando un portale per spedizioni stagionale",
        OPTIONS_PORTAL_TOOLTIP = "Avvisa anche usando un portale per spedizioni della stagione attuale sotto l'80% di integrità.",
        OPTIONS_FOLLOWUP = "Avvisa dopo una perdita di integrità",
        OPTIONS_FOLLOWUP_TOOLTIP = "Avvisa anche dopo una perdita di integrità sotto il 50% in un'istanza o voragine.",
        MAJOR_WARNING_CHANGED = "Avviso principale %s.",
        FOLLOWUP_WARNING_CHANGED = "Avvisi principali successivi %s.",
        PORTAL_WARNING_CHANGED = "Avvisi dei portali per spedizioni stagionali %s.",
        MAJOR_WARNING_STATUS = "L'avviso principale è %s.",
        FOLLOWUP_WARNING_STATUS = "Gli avvisi successivi sono %s.",
        PORTAL_WARNING_STATUS = "Gli avvisi dei portali per spedizioni stagionali sono %s.",
        ENABLED = "attivato", DISABLED = "disattivato",
        ENABLED_PLURAL = "attivati", DISABLED_PLURAL = "disattivati",
        HELP_WARNING = "Usa /ddt warning on o /ddt warning off.",
        HELP_FOLLOWUP = "Usa /ddt warning followup on o /ddt warning followup off.",
        HELP_PORTAL = "Usa /ddt warning portal on o /ddt warning portal off.",
    },
    ptBR = {
        NO_DURABILITY = "Nenhum item equipado com durabilidade foi encontrado.",
        CURRENT_DURABILITY = "Durabilidade atual: %s.",
        LOW_DURABILITY = "DURABILIDADE BAIXA: %.1f%%",
        DURABILITY_LOSS = "Você perdeu |cffffffff%.1f%%|r de durabilidade. Durabilidade restante: %s.",
        OPTIONS_MAJOR = "Ativar aviso principal",
        OPTIONS_MAJOR_TOOLTIP = "Exibe um texto grande e toca um som ao entrar em uma instância ou imersão com menos de 80% de durabilidade.",
        OPTIONS_PORTAL = "Avisar ao usar um portal de masmorra da temporada",
        OPTIONS_PORTAL_TOOLTIP = "Também avisa ao usar um portal de masmorra da temporada atual com menos de 80% de durabilidade.",
        OPTIONS_FOLLOWUP = "Avisar após perda de durabilidade",
        OPTIONS_FOLLOWUP_TOOLTIP = "Também avisa após uma perda de durabilidade abaixo de 50% dentro de uma instância ou imersão.",
        MAJOR_WARNING_CHANGED = "Aviso principal %s.",
        FOLLOWUP_WARNING_CHANGED = "Avisos principais posteriores %s.",
        PORTAL_WARNING_CHANGED = "Avisos de portal de masmorra da temporada %s.",
        MAJOR_WARNING_STATUS = "O aviso principal está %s.",
        FOLLOWUP_WARNING_STATUS = "Os avisos posteriores estão %s.",
        PORTAL_WARNING_STATUS = "Os avisos de portal de masmorra da temporada estão %s.",
        ENABLED = "ativado",
        DISABLED = "desativado",
        ENABLED_PLURAL = "ativados",
        DISABLED_PLURAL = "desativados",
        HELP_WARNING = "Use /ddt warning on ou /ddt warning off.",
        HELP_FOLLOWUP = "Use /ddt warning followup on ou /ddt warning followup off.",
        HELP_PORTAL = "Use /ddt warning portal on ou /ddt warning portal off.",
    },
    ruRU = {
        NO_DURABILITY = "Не найдено экипированных предметов с прочностью.",
        CURRENT_DURABILITY = "Текущая прочность: %s.",
        LOW_DURABILITY = "НИЗКАЯ ПРОЧНОСТЬ: %.1f%%",
        DURABILITY_LOSS = "Вы потеряли |cffffffff%.1f%%|r прочности. Осталось прочности: %s.",
        OPTIONS_MAJOR = "Включить главное предупреждение",
        OPTIONS_MAJOR_TOOLTIP = "Показывает крупный текст и воспроизводит звук при входе в подземелье или вылазку с прочностью ниже 80 %.",
        OPTIONS_PORTAL = "Предупреждать при использовании сезонного портала",
        OPTIONS_PORTAL_TOOLTIP = "Также предупреждает при использовании портала в подземелье текущего сезона с прочностью ниже 80 %.",
        OPTIONS_FOLLOWUP = "Предупреждать после потери прочности",
        OPTIONS_FOLLOWUP_TOOLTIP = "Также предупреждает после падения прочности ниже 50 % внутри подземелья или вылазки.",
        MAJOR_WARNING_CHANGED = "Главное предупреждение %s.",
        FOLLOWUP_WARNING_CHANGED = "Последующие главные предупреждения %s.",
        PORTAL_WARNING_CHANGED = "Предупреждения о сезонных порталах %s.",
        MAJOR_WARNING_STATUS = "Главное предупреждение %s.",
        FOLLOWUP_WARNING_STATUS = "Последующие предупреждения %s.",
        PORTAL_WARNING_STATUS = "Предупреждения о сезонных порталах %s.",
        ENABLED = "включено", DISABLED = "отключено",
        ENABLED_PLURAL = "включены", DISABLED_PLURAL = "отключены",
        HELP_WARNING = "Используйте /ddt warning on или /ddt warning off.",
        HELP_FOLLOWUP = "Используйте /ddt warning followup on или /ddt warning followup off.",
        HELP_PORTAL = "Используйте /ddt warning portal on или /ddt warning portal off.",
    },
    koKR = {
        NO_DURABILITY = "내구도가 있는 착용 장비가 없습니다.",
        CURRENT_DURABILITY = "현재 내구도: %s.",
        LOW_DURABILITY = "내구도 낮음: %.1f%%",
        DURABILITY_LOSS = "내구도를 |cffffffff%.1f%%|r 잃었습니다. 남은 내구도: %s.",
        OPTIONS_MAJOR = "주요 경고 사용",
        OPTIONS_MAJOR_TOOLTIP = "내구도가 80% 미만일 때 인스턴스 또는 구렁에 입장하면 큰 글씨를 표시하고 소리를 재생합니다.",
        OPTIONS_PORTAL = "시즌 던전 차원문 사용 시 경고",
        OPTIONS_PORTAL_TOOLTIP = "내구도가 80% 미만일 때 현재 시즌 던전 차원문을 사용해도 경고합니다.",
        OPTIONS_FOLLOWUP = "내구도 손실 후 경고",
        OPTIONS_FOLLOWUP_TOOLTIP = "인스턴스 또는 구렁 안에서 내구도가 50% 미만으로 떨어지면 경고합니다.",
        MAJOR_WARNING_CHANGED = "주요 경고가 %s.",
        FOLLOWUP_WARNING_CHANGED = "후속 주요 경고가 %s.",
        PORTAL_WARNING_CHANGED = "시즌 던전 차원문 경고가 %s.",
        MAJOR_WARNING_STATUS = "주요 경고가 %s.",
        FOLLOWUP_WARNING_STATUS = "후속 경고가 %s.",
        PORTAL_WARNING_STATUS = "시즌 던전 차원문 경고가 %s.",
        ENABLED = "활성화되었습니다", DISABLED = "비활성화되었습니다",
        ENABLED_PLURAL = "활성화되었습니다", DISABLED_PLURAL = "비활성화되었습니다",
        HELP_WARNING = "/ddt warning on 또는 /ddt warning off를 사용하세요.",
        HELP_FOLLOWUP = "/ddt warning followup on 또는 /ddt warning followup off를 사용하세요.",
        HELP_PORTAL = "/ddt warning portal on 또는 /ddt warning portal off를 사용하세요.",
    },
    zhCN = {
        NO_DURABILITY = "未找到有耐久度的已装备物品。",
        CURRENT_DURABILITY = "当前耐久度：%s。",
        LOW_DURABILITY = "耐久度过低：%.1f%%",
        DURABILITY_LOSS = "你损失了 |cffffffff%.1f%%|r 耐久度。剩余耐久度：%s。",
        OPTIONS_MAJOR = "启用醒目警告",
        OPTIONS_MAJOR_TOOLTIP = "耐久度低于 80% 时进入副本或地下堡，显示大号文字并播放声音。",
        OPTIONS_PORTAL = "使用赛季地下城传送门时警告",
        OPTIONS_PORTAL_TOOLTIP = "耐久度低于 80% 时使用当前赛季地下城传送门也会警告。",
        OPTIONS_FOLLOWUP = "耐久度损失后警告",
        OPTIONS_FOLLOWUP_TOOLTIP = "在副本或地下堡内耐久度损失至 50% 以下时也会警告。",
        MAJOR_WARNING_CHANGED = "醒目警告已%s。",
        FOLLOWUP_WARNING_CHANGED = "后续醒目警告已%s。",
        PORTAL_WARNING_CHANGED = "赛季地下城传送门警告已%s。",
        MAJOR_WARNING_STATUS = "醒目警告已%s。",
        FOLLOWUP_WARNING_STATUS = "后续警告已%s。",
        PORTAL_WARNING_STATUS = "赛季地下城传送门警告已%s。",
        ENABLED = "启用", DISABLED = "禁用",
        ENABLED_PLURAL = "启用", DISABLED_PLURAL = "禁用",
        HELP_WARNING = "使用 /ddt warning on 或 /ddt warning off。",
        HELP_FOLLOWUP = "使用 /ddt warning followup on 或 /ddt warning followup off。",
        HELP_PORTAL = "使用 /ddt warning portal on 或 /ddt warning portal off。",
    },
    zhTW = {
        NO_DURABILITY = "找不到有耐久度的已裝備物品。",
        CURRENT_DURABILITY = "目前耐久度：%s。",
        LOW_DURABILITY = "耐久度過低：%.1f%%",
        DURABILITY_LOSS = "你損失了 |cffffffff%.1f%%|r 耐久度。剩餘耐久度：%s。",
        OPTIONS_MAJOR = "啟用醒目警告",
        OPTIONS_MAJOR_TOOLTIP = "耐久度低於 80% 時進入副本或探究，顯示大型文字並播放音效。",
        OPTIONS_PORTAL = "使用賽季地城傳送門時警告",
        OPTIONS_PORTAL_TOOLTIP = "耐久度低於 80% 時使用當前賽季地城傳送門也會警告。",
        OPTIONS_FOLLOWUP = "耐久度損失後警告",
        OPTIONS_FOLLOWUP_TOOLTIP = "在副本或探究內耐久度損失至 50% 以下時也會警告。",
        MAJOR_WARNING_CHANGED = "醒目警告已%s。",
        FOLLOWUP_WARNING_CHANGED = "後續醒目警告已%s。",
        PORTAL_WARNING_CHANGED = "賽季地城傳送門警告已%s。",
        MAJOR_WARNING_STATUS = "醒目警告已%s。",
        FOLLOWUP_WARNING_STATUS = "後續警告已%s。",
        PORTAL_WARNING_STATUS = "賽季地城傳送門警告已%s。",
        ENABLED = "啟用", DISABLED = "停用",
        ENABLED_PLURAL = "啟用", DISABLED_PLURAL = "停用",
        HELP_WARNING = "使用 /ddt warning on 或 /ddt warning off。",
        HELP_FOLLOWUP = "使用 /ddt warning followup on 或 /ddt warning followup off。",
        HELP_PORTAL = "使用 /ddt warning portal on 或 /ddt warning portal off。",
    },
}

locales.enGB = locales.enUS

DDT.L = locales[GetLocale()] or locales.enUS
